Resources
collebrusco/ECE-461L-Orange pull request #50
Opened 2023-11-08 01:58 UTC by spencshis-prog

2023-11-08 04:00 UTC, weii41392 commented
There are many conflicts between `dev` and `resources` branches. Would you create a new branch based off from `dev` and add `resources.py`?

2023-11-09 17:42 UTC, weii41392 requested changes

2023-11-09 17:42 UTC, weii41392 commented on backend/app/resources.py
> +@require_jwt
```suggestion
```
GET `/resources` is not protected route

2023-11-09 17:42 UTC, weii41392 commented on backend/app/resources.py
> +    return jsonify(resources_collection)
Not sure if this will work. Try `collection.find()` and only collect the fields specified in OpenAPI.

2023-11-09 17:42 UTC, weii41392 commented on backend/app/resources.py
> +@app.route('/resources/{resource_title}/checkout', methods=['POST'])
It's `<some_parameter>`. Check https://flask.palletsprojects.com/en/3.0.x/api/#url-route-registrations

2023-11-09 17:42 UTC, weii41392 commented on backend/app/resources.py
> +        if resource is None:
Also check if `project` exists

2023-11-09 17:42 UTC, weii41392 commented on backend/app/resources.py
> +        resource["availability"] = resource["availability"] + amount
Logic here is weird

2023-11-09 17:45 UTC, weii41392 commented on backend/app/resources.py
> +        if resource is None:
And probably check if the user is allowed to do this op, i.e. if the user is in this project

2023-11-09 18:04 UTC, mimiliaogo commented
You need to check if the user exists in the db for every function you use @require_jwt.

2023-11-10 21:45 UTC, weii41392 requested changes
The current version still doesn't work. Please revise these and test them with API testing software like Postman.

2023-11-10 21:45 UTC, weii41392 commented on backend/app/resources.py
> +def all_resources(user: User):
```suggestion
def all_resources():
```

2023-11-10 21:45 UTC, weii41392 commented on backend/app/resources.py
> +        return jsonify(resource), 200
```suggestion
        resources_collection.update_one({"title": resource_title}, {"$set": {"availability": resource["availability"]}})
        projects_collection.update_one({'title': data.get('project_title')}, {"$set": {f"resources.{resource_title}": project["resources"][resource_title]}})
        
        return parse_json(resource), 200
```

2023-11-10 21:45 UTC, weii41392 commented on backend/app/resources.py
> +        return jsonify(resource), 200
```suggestion
        resources_collection.update_one({"title": resource_title}, {"$set": {"availability": resource["availability"]}})
        projects_collection.update_one({'title': data.get('project_title')}, {"$set": {f"resources.{resource_title}": project["resources"][resource_title]}})
        
        return parse_json(resource), 200
```

2023-11-10 23:37 UTC, weii41392 commented on backend/app/resources.py
> +        if int(resource["availability"]) < int(amount):
What is the meaning of storing these numbers as strings?
I am open if the API works the same, but in this case I get `availability` as strings in GET `/resources` after checkin/checkout, causing more problems.

```
[
	{
		"_id": {
			"$oid": "654ebdcd626a7e314b0af231"
		},
		"availability": "0",
		"capacity": 100,
		"created_at": {
			"$date": "2023-11-10T23:33:33.040Z"
		},
		"title": "HW Set 1"
	},
	{
		"_id": {
			"$oid": "654ebdcd626a7e314b0af232"
		},
		"availability": 200,
		"capacity": 200,
		"created_at": {
			"$date": "2023-11-10T23:33:33.040Z"
		},
		"title": "HW Set 2"
	},
	{
		"_id": {
			"$oid": "654ebdcd626a7e314b0af233"
		},
		"availability": 300,
		"capacity": 300,
		"created_at": {
			"$date": "2023-11-10T23:33:33.040Z"
		},
		"title": "HW Set 3"
	}
]
```

2023-11-11 04:28 UTC, weii41392 approved these changes

2023-11-11 04:28 UTC, merged